database: h2

spring:
  main:
    banner-mode: off
  application:
    name: auction-backend
  datasource:
#    Dockerfile connection
#    url: jdbc:postgresql://host.docker.internal:5432/ptsoftware
    url: jdbc:postgresql://localhost:5432/ptsoftware
    username: ptsoftware
    password: Password123
    hikari:
      data-source-properties:
        stringtype: unspecified
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: false
      hibernate.types.print.banner: false
  flyway:
    enabled: true
    schemas:
      - active
      - flyway
    default-schema: flyway
    baseline-on-migrate: true
    user: ptsoftware
    password: Password123
    baseline-version: 0.0.0
    table: version_history_${spring.application.name}
    out-of-order: true
    validate-migration-naming: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    schema: classpath*:db/${database}/schema.sql
#    data: classpath*:db/${database}/data.sql
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  security:
#    user:
#      name: jan
#      password: 1234
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ
